CREATE TABLE FoodRecognitions
(
    ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    UserID BIGINT UNSIGNED,
    ResultJson JSON,
    Status BIGINT UNSIGNED,
    ErrorMessage VARCHAR(256) DEFAULT '',
    CreateTS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(ID)
);